class Py4DGeoError(Exception):
    pass
